/** Kinship in the family's own languages. English is generated by
 * relationship-path; Persian and French are looked up here from the same
 * result, because Persian does not have "uncle" - it has عمو and دایی, and
 * which one depends on the side and on who the link runs through. */

import type { Lang } from "./i18n";
import type { KinshipVoice, RelationshipResult } from "./relationship-path";

type Word = { fa?: string; fr?: string };

const greats = (steps: number, base: string) => steps <= 1 ? base : steps === 2 ? `grand${base}` : `${"great-".repeat(steps - 2)}grand${base}`;

/** the Persian and French for one result, or null to fall back to English */
function words(result: RelationshipResult): Word | null {
  const { up, down, side, viaTheirs, to } = result;
  if (up === undefined || down === undefined) {
    if (result.relationship === "husband") return { fa: "شوهر", fr: "mari" };
    if (result.relationship === "wife") return { fa: "زن", fr: "femme" };
    if (result.relationship === "spouse") return { fa: "همسر", fr: "conjoint" };
    return null;
  }
  const male = to.gender === "male", female = to.gender === "female";
  const boy = (m: string, f: string, n: string) => male ? m : female ? f : n;
  if (up === 0) {
    if (down === 1) return { fa: boy("پسر", "دختر", "فرزند"), fr: boy("fils", "fille", "enfant") };
    if (down === 2) return { fa: "نوه", fr: boy("petit-fils", "petite-fille", "petit-enfant") };
    if (down === 3) return { fa: "نتیجه", fr: boy("arrière-petit-fils", "arrière-petite-fille", "arrière-petit-enfant") };
    return { fa: "نبیره", fr: `${"arrière-".repeat(down - 2)}${boy("petit-fils", "petite-fille", "petit-enfant")}` };
  }
  if (down === 0) {
    const sideFa = side === "paternal" ? " پدری" : side === "maternal" ? " مادری" : "";
    const sideFr = side === "paternal" ? " paternel" : side === "maternal" ? " maternel" : "";
    const sideFrF = side === "paternal" ? " paternelle" : side === "maternal" ? " maternelle" : "";
    if (up === 1) return { fa: boy("پدر", "مادر", "والد"), fr: boy("père", "mère", "parent") };
    if (up === 2) return { fa: `${boy("پدربزرگ", "مادربزرگ", "پدربزرگ یا مادربزرگ")}${sideFa}`, fr: `${boy("grand-père", "grand-mère", "grand-parent")}${male ? sideFr : female ? sideFrF : ""}` };
    return { fa: `${boy("جد", "جده", "جد")}${sideFa}`, fr: `${"arrière-".repeat(up - 2)}${boy("grand-père", "grand-mère", "grand-parent")}${male ? sideFr : female ? sideFrF : ""}` };
  }
  if (up === 1 && down === 1) return { fa: boy("برادر", "خواهر", "خواهر یا برادر"), fr: boy("frère", "sœur", "frère ou sœur") };
  if (up === 1) {
    // nephews and nieces are named by the sibling they come through
    const viaBrother = viaTheirs?.gender === "male", viaSister = viaTheirs?.gender === "female";
    const stem = viaBrother ? "برادرزاده" : viaSister ? "خواهرزاده" : "برادرزاده یا خواهرزاده";
    const fr = boy("neveu", "nièce", "neveu ou nièce");
    if (down === 2) return { fa: stem, fr };
    return { fa: `${greats(down - 1, "")}${stem}`.replace(/^grand/, "نوهٔ ").replace(/great-/g, ""), fr: `${"arrière-".repeat(down - 2)}petit-${fr}` };
  }
  if (down === 1) {
    const paternal = side === "paternal", maternal = side === "maternal";
    const fa = paternal ? boy("عمو", "عمه", "عمو یا عمه") : maternal ? boy("دایی", "خاله", "دایی یا خاله") : boy("عمو یا دایی", "عمه یا خاله", "عمو، دایی، عمه یا خاله");
    const fr = `${boy("oncle", "tante", "oncle ou tante")}${paternal ? (male ? " paternel" : female ? " paternelle" : "") : maternal ? (male ? " maternel" : female ? " maternelle" : "") : ""}`;
    if (up === 2) return { fa, fr };
    return { fa: `${fa} بزرگ`, fr: `${"arrière-".repeat(up - 3)}grand-${fr}` };
  }
  // cousins: Persian names them by the aunt or uncle they come through
  const degree = Math.min(up, down) - 1;
  const removed = Math.abs(up - down);
  if (degree === 1 && removed === 0) {
    const throughMale = viaTheirs?.gender === "male", throughFemale = viaTheirs?.gender === "female";
    const paternal = side === "paternal", maternal = side === "maternal";
    const link = paternal ? (throughMale ? "عمو" : throughFemale ? "عمه" : "عمو") : maternal ? (throughMale ? "دایی" : throughFemale ? "خاله" : "دایی") : null;
    return { fa: link ? `${boy("پسر", "دختر", "فرزند")}${link}` : "پسرعمو یا دخترعمو", fr: boy("cousin germain", "cousine germaine", "cousin germain") };
  }
  const ordFr = ["", "germain", "issu de germain", "au troisième degré", "au quatrième degré"][degree] ?? `au ${degree}e degré`;
  const removedFr = removed ? ` (${removed === 1 ? "une" : removed} génération${removed > 1 ? "s" : ""} d'écart)` : "";
  return { fa: `${boy("پسر", "دختر", "فرزند")}${side === "maternal" ? "دایی" : "عمو"}ی دور${removed ? " (نسل متفاوت)" : ""}`, fr: `${boy("cousin", "cousine", "cousin")} ${ordFr}${removedFr}` };
}

/** "your paternal uncle" / "عموی شما" / "votre oncle paternel" */
export function kinshipLabel(result: RelationshipResult | null, lang: Lang, voice: KinshipVoice = "your"): string | null {
  if (!result || result.relationship === "not connected in the records") return null;
  if (result.relationship === "the same person") return voice === "your" ? (lang === "fa" ? "شما" : lang === "fr" ? "vous" : "you") : null;
  if (result.relationship.startsWith("related by marriage")) {
    const through = result.relationship.includes("through ") ? result.relationship.split("through ")[1] : null;
    if (lang === "fa") return through ? `خویشاوند سببی از طریق ${through}` : "خویشاوند سببی";
    if (lang === "fr") return through ? `parent par alliance, via ${through}` : "parent par alliance";
    return `${voice} relative by marriage${through ? `, via ${through}` : ""}`;
  }
  const word = words(result);
  if (lang === "fa" && word?.fa) {
    const owner = voice === "your" ? "شما" : "او";
    // the ezafe: ZWNJ + ی after a silent ه (خاله‌ی), a bare ی after a vowel letter (عموی), nothing written after a consonant
    const stem = word.fa.endsWith("ه") ? `${word.fa}‌ی` : /[وای]$/.test(word.fa) ? `${word.fa}ی` : word.fa;
    return `${stem} ${owner}`;
  }
  if (lang === "fr" && word?.fr) {
    const feminine = /^(mère|grand-mère|sœur|fille|petite-fille|nièce|tante|cousine|femme)/.test(word.fr) || /^arrière-(grand-mère|petite-fille)/.test(word.fr);
    const owner = voice === "your" ? (word.fr.startsWith("arrière") || /^[aeiouâéè]/.test(word.fr) ? "votre" : "votre") : feminine ? "sa" : "son";
    return `${owner} ${word.fr}`;
  }
  return `${voice} ${result.relationship}`;
}
