#!/usr/bin/env node
// Generate lib/world-map-paths.ts from Natural Earth countries (110m).
//
// The Map view's original "world" was six hand-drawn blobs, and the marker
// table was eyeballed percentages tuned to those blobs. This script replaces
// the geometry with the real thing: world-atlas countries-110m (Natural Earth
// data, public domain), decoded from TopoJSON, projected equirectangular into
// the map's 1000x500 viewBox — one path per country so borders are visible.
// Marker positions in lib/archive-views.ts use the same projection from real
// lat/lon, so places land where the coastlines say they should.
//
// Antarctica is dropped (it doubles the ink for a continent no record cites).
//
// Usage: node scripts/generate_world_map.mjs   (network: fetches world-atlas)
import { writeFile } from "node:fs/promises";

const SOURCE = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";
const WIDTH = 1000, HEIGHT = 500;

const topology = await (await fetch(SOURCE)).json();
const { scale, translate } = topology.transform;
// TopoJSON arcs are delta-encoded quantized coordinates
const arcs = topology.arcs.map((arc) => {
  let x = 0, y = 0;
  return arc.map(([dx, dy]) => {
    x += dx; y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
  });
});
const ring = (arcIndexes) => {
  const points = [];
  for (const index of arcIndexes) {
    const arc = index >= 0 ? arcs[index] : [...arcs[~index]].reverse();
    // consecutive arcs share their joint point
    points.push(...(points.length ? arc.slice(1) : arc));
  }
  return points;
};
const project = ([lon, lat]) => [
  Math.round(((lon + 180) / 360) * WIDTH * 10) / 10,
  Math.round(((90 - lat) / 180) * HEIGHT * 10) / 10,
];
// A ring that crosses the antimeridian (Russia, Fiji) would draw a horizontal
// line across the whole map; split it at the jump and close each part at the
// map edge instead.
const ringPath = (points) => {
  const projected = points.map(project);
  const parts = [[projected[0]]];
  let [lastX, lastY] = projected[0];
  for (const [x, y] of projected.slice(1)) {
    if (Math.abs(x - lastX) < 0.15 && Math.abs(y - lastY) < 0.15) continue;
    if (Math.abs(x - lastX) > WIDTH / 2) {
      const midY = Math.round(((y + lastY) / 2) * 10) / 10;
      parts[parts.length - 1].push([lastX < WIDTH / 2 ? 0 : WIDTH, midY]);
      parts.push([[x < WIDTH / 2 ? 0 : WIDTH, midY]]);
    }
    parts[parts.length - 1].push([x, y]);
    lastX = x; lastY = y;
  }
  return parts
    .filter((part) => part.length > 2)
    .map((part) => "M" + part.map(([x, y]) => `${x} ${y}`).join("L") + "Z")
    .join("");
};

const paths = [];
for (const geometry of topology.objects.countries.geometries) {
  if (geometry.id === "010") continue; // Antarctica
  const polygons = geometry.type === "Polygon" ? [geometry.arcs] : geometry.type === "MultiPolygon" ? geometry.arcs : [];
  const d = polygons.flatMap((rings) => rings.map((indexes) => ring(indexes)).filter((points) => points.length > 3).map(ringPath)).join("");
  if (d) paths.push(d);
}

const output = `// Generated by scripts/generate_world_map.mjs from world-atlas countries-110m
// (Natural Earth, public domain). Equirectangular, viewBox 0 0 ${WIDTH} ${HEIGHT},
// one path per country, Antarctica omitted. Do not edit by hand.
export const WORLD_COUNTRY_PATHS: string[] = ${JSON.stringify(paths)};
`;
await writeFile("lib/world-map-paths.ts", output);
console.log(`countries: ${paths.length}, output: ${Math.round(output.length / 1024)} KB`);
